[package]
name = "memalert"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.78", features = ["backtrace"] }
env_logger = "0.10.1"
futures = "0.3.30"
log = "0.4.20"
nameof = "1.2.2"
nix = { version = "0.27.1", features = ["feature"] }
tokio = { version = "1.35.1", features = [
	"macros",
	"rt",
	"signal",
	"sync",
	"time",
] }
tokio-util = "0.7.10"
zbus = "3.14.1"

[profile.release]
codegen-units = 1
lto = true
strip = true
